version: "3"

services:
  api:
    build: .
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html
    ports:
      - 81:80
      - 444:443
    extra_hosts:
      - "localhost:127.0.0.1"

  postgres:
    image: postgres:11-alpine
    ports:
      - 5444:5432
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api